# Generated by Django 3.1.2 on 2021-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20210406_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='article',
            name='small_poster',
        ),
        migrations.AddField(
            model_name='article',
            name='is_promote',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='poster',
            field=models.ImageField(upload_to='articles/'),
        ),
    ]
